import type { AppProps } from 'next/app'
import '../styles/globals.css'
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Practice Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>

      <main>
        <Component {...pageProps} />
      </main>

      <footer></footer>
    </>
  )
}

export default MyApp
